doctrine:
    dbal:
        driver:   pdo_mysql
        host:     127.0.0.1
        port:     null
        dbname:   oc_blog
        user:     root
        password: null
        charset:  UTF8

swiftmailer:
    config:
        host:     ssl0.ovh.net
        port:     587
        username: blog.contact@bostjancic.fr
        password: blogcontact