imports:
    - { ressource: parameters.yml}

doctrine:
    dbal:
        driver:   pdo_mysql
        host:     127.0.0.1
        port:     null
        dbname:   oc_blog
        user:     root
        password: null
        charset:  UTF8